package main

// file generated by
// github.com/mh-cbon/jsoner
// do not edit

import (
	"bytes"
	"encoding/json"
	"io"
)

// JSONController is jsoner of *Controller.
type JSONController struct {
	embed *Controller
}

// NewJSONController constructs a jsoner of *Controller
func NewJSONController(embed *Controller) *JSONController {
	ret := &JSONController{
		embed: embed,
	}
	return ret
}

// GetByID reads json, outputs json.
// the json input must provide a key/value for each params.
func (t *JSONController) GetByID(urlID int) (io.Reader, error) {
	var ret io.Reader
	var retErr error

	retVar0 := t.embed.GetByID(urlID)

	out, encErr := json.Marshal([]interface{}{retVar0})
	if encErr != nil {
		retErr = encErr
	} else {
		var b bytes.Buffer
		b.Write(out)
		ret = &b
	}

	return ret, retErr
}

// UpdateByID reads json, outputs json.
// the json input must provide a key/value for each params.
func (t *JSONController) UpdateByID(urlID int, reqBody io.Reader) (io.Reader, error) {
	var ret io.Reader
	var retErr error

	var decBody *Tomate
	decErr := json.NewDecoder(reqBody).Decode(decBody)
	if decErr != nil {
		return nil, decErr
	}

	retVar1 := t.embed.UpdateByID(urlID, decBody)

	out, encErr := json.Marshal([]interface{}{retVar1})
	if encErr != nil {
		retErr = encErr
	} else {
		var b bytes.Buffer
		b.Write(out)
		ret = &b
	}

	return ret, retErr
}

// DeleteByID reads json, outputs json.
// the json input must provide a key/value for each params.
func (t *JSONController) DeleteByID(reqID int) (io.Reader, error) {
	var ret io.Reader
	var retErr error

	retVar2 := t.embed.DeleteByID(reqID)

	out, encErr := json.Marshal([]interface{}{retVar2})
	if encErr != nil {
		retErr = encErr
	} else {
		var b bytes.Buffer
		b.Write(out)
		ret = &b
	}

	return ret, retErr
}
